"""empty message

Revision ID: 236560e6960d
Revises: 6f4739033077
Create Date: 2024-05-16 23:24:02.509914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '236560e6960d'
down_revision = '6f4739033077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_category', schema=None) as batch_op:
        batch_op.drop_constraint('post_category_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('post_category_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_tag', schema=None) as batch_op:
        batch_op.drop_constraint('post_tag_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('post_tag_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_tag_ibfk_2', 'tag', ['tag_id'], ['id'])
        batch_op.create_foreign_key('post_tag_ibfk_1', 'post', ['post_id'], ['id'])

    with op.batch_alter_table('post_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_category_ibfk_2', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('post_category_ibfk_1', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###
