"""Add created_at to VisaApplication

Revision ID: 5f1c60511f81
Revises: d6ba74defb8c
Create Date: 2024-05-22 03:21:51.616989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1c60511f81'
down_revision = 'd6ba74defb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
