"""empty message

Revision ID: 6610b9c1093e
Revises: 5818bbd10eb1
Create Date: 2024-05-21 02:07:50.072716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6610b9c1093e'
down_revision = '5818bbd10eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('passport_number', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visa_application')
    # ### end Alembic commands ###
