"""empty message

Revision ID: 6ec2dd435934
Revises: 90342147863e
Create Date: 2024-08-23 00:40:49.710585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec2dd435934'
down_revision = '90342147863e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visa_application', sa.Column('visa_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visa_application', 'visa_type')
    # ### end Alembic commands ###
