"""empty message

Revision ID: 6f4739033077
Revises: 3f1017568bc0
Create Date: 2024-05-16 02:38:55.704064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f4739033077'
down_revision = '3f1017568bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
