"""empty message

Revision ID: 783d0dd162f1
Revises: ae005957ba7e
Create Date: 2024-05-15 19:21:12.636766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783d0dd162f1'
down_revision = 'ae005957ba7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destination', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
