"""empty message

Revision ID: ae005957ba7e
Revises: d4f72e4da450
Create Date: 2024-05-15 01:13:57.593151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae005957ba7e'
down_revision = 'd4f72e4da450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.Text(), nullable=False))
        batch_op.drop_column('subcontent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcontent', mysql.TEXT(), nullable=False))
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
