"""empty message

Revision ID: b978a0ac2ffe
Revises: 8d06b589dfc3
Create Date: 2024-05-27 01:06:43.903256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b978a0ac2ffe'
down_revision = '8d06b589dfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('subscribed_at')

    # ### end Alembic commands ###
