"""empty message

Revision ID: cd660cfaa445
Revises: 6610b9c1093e
Create Date: 2024-05-21 02:54:49.831111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd660cfaa445'
down_revision = '6610b9c1093e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.drop_column('passport_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visa_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_number', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
