"""empty message

Revision ID: d6ba74defb8c
Revises: cd660cfaa445
Create Date: 2024-05-21 13:04:51.527189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6ba74defb8c'
down_revision = 'cd660cfaa445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_expiration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_expiration', mysql.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###
