"""empty message

Revision ID: e93c7491f931
Revises: b978a0ac2ffe
Create Date: 2024-05-27 02:24:53.745048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e93c7491f931'
down_revision = 'b978a0ac2ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userpostid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('response_text', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('date_posted', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='comment_ibfk_1'),
    sa.ForeignKeyConstraint(['userpostid'], ['post.id'], name='comment_ibfk_2'),
    sa.PrimaryKeyConstraint('comment_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
