"""empty message

Revision ID: fa765ee671a5
Revises: b5ee9ddefcbb
Create Date: 2024-05-26 22:11:35.177206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa765ee671a5'
down_revision = 'b5ee9ddefcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_subject', sa.String(length=100), nullable=True))
        batch_op.alter_column('contact_message',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_column('contact_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_no', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('contact_message',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('contact_subject')

    # ### end Alembic commands ###
